name: Release

# Triggered by pushing on main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      - name: Build
        run: hugo --minify

      # - name: Generate App token
      #   id: generate-token
      #   uses: actions/create-github-app-token@v2
      #   with:
      #     app-id: ${{ vars.APP_ID }}
      #     private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        # env:
        #   GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          cd public
          # gh api octocat
          git config user.email 'mikezom3721@gmail.com'
          git config user.name 'mikezom'
          # gh auth status
          git add .
          git commit -m 'Update site'
          git push origin main